name: todo_list_offline
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rive: ^0.7.33
  flutter_bloc: ^7.3.3
  equatable: ^2.0.3
  dartz: ^0.10.0
  shimmer: ^2.0.0
  google_fonts: ^2.1.0  
  flutter_modular: ^4.2.0
  flutter_icons: ^1.1.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/

 